name: conda

on:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

env:
  PYTEST_ADOPTS: "--color=yes"

jobs:
  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2
      with:
        ref: latest

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: binder/environment.yml

    - name: Install testing packages
      run: conda install -c conda-forge -y pytest nbval invoke

    - name: Test all
      run: invoke test.all
