name: workflow

on:
  push:
    branches-ignore:
      - 'stable'
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Install testing packages
      run: python -m pip install --upgrade pip pytest-cov nbval pycodestyle

    - name: Install package
      run: python -m pip install .

    - name: Unit tests
      run: make test-unittests
      if: matrix.os != 'ubuntu-latest'

    - name: Unit tests with coverage
      run: make test-coverage
      if: matrix.os == 'ubuntu-latest'

    - name: Documentation tests
      run: make test-docs

    - name: Jupyter notebook tests
      run: make test-ipynb

    - name: Python code style
      run: make test-pycodestyle

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'

